FROM node:20-alpine
WORKDIR /app

COPY package.json package.json
COPY apps/admin/package.json apps/admin/package.json

RUN npm install

COPY . .

WORKDIR /app/apps/admin

EXPOSE 3000

CMD ["sh", "-c", "npm run build && npm run start"]
