FROM node:20-alpine
WORKDIR /app

COPY package.json package.json
COPY apps/api/package.json apps/api/package.json
COPY packages/db/package.json packages/db/package.json
COPY packages/shared/package.json packages/shared/package.json

RUN npm install

COPY . .

WORKDIR /app/apps/api

EXPOSE 3001

CMD ["sh", "-c", "npm run build && node dist/main.js"]
